# Generated by Django 5.1.5 on 2026-03-17 08:43

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Markdown — steps, context, constraints for the coordinator.')),
                ('coordinator_model', models.CharField(default='gemini-2.5-pro', help_text='Strong model for the coordinator.', max_length=50, validators=[core.models.validate_model_choice])),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_text', models.CharField(blank=True, help_text='Free-text schedule for the coordinator (e.g. "every weekday at 8am").', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_report', models.TextField(blank=True, help_text='The coordinator final synthesis after all specialists report back.')),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.briefing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(help_text='Agent name (matches filename in agents/ dir).', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('container_id', models.CharField(blank=True, help_text='Docker container ID.', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True, help_text='What this specialist reported back.')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Structured data from the specialist.')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='core.run')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='briefing',
            index=models.Index(fields=['owner', 'is_active'], name='core_briefi_owner_i_329f00_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['briefing', 'status'], name='core_run_briefin_a27642_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['created_at'], name='core_run_created_0f22f6_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['run', 'status'], name='core_agentr_run_id_d703b2_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent_name'], name='core_agentr_agent_n_45385d_idx'),
        ),
    ]
