# Generated by Django 5.1.5 on 2026-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100, unique=True)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of agent .md + skill deps.', max_length=64)),
                ('image_tag', models.CharField(help_text='Docker image tag, e.g. fuzzyclaw-agent-summarizer:latest', max_length=200)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('build_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['agent_name'],
            },
        ),
    ]
