# Generated by Django 5.1.5 on 2026-04-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='user_notes',
            field=models.TextField(blank=True, help_text='Free-form user annotations. Separate from the execution-managed fields above.'),
        ),
        migrations.AddField(
            model_name='run',
            name='user_notes',
            field=models.TextField(blank=True, help_text='Free-form user annotations. Separate from the execution-managed fields above.'),
        ),
    ]
