# Generated by Django 5.1.5 on 2026-04-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agentrun_user_notes_run_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID of the launch_coordinator Celery task. Used by the cancel action to revoke the task.', max_length=100),
        ),
    ]
